[Build]  CMake install Python dist-info
Part of #58. Install a minimal dist-info alongside the Python sources.
This means attempting to overwrite a CMake installation using
`pip install` will error like:

> ERROR: Cannot uninstall openassetio-mediacreation 1.0.0a7,
> RECORD file not found.
> Hint: The package was installed by cmake.

* `INSTALLER` is used by `pip` to provide the competing packager name
  ("cmake" in the example hint above).
* `METADATA` is mandatory according to the docs. It has the minimal
  contents required to be valid.
* `REQUESTED` is an empty flag file to signal that the package was
  installed individually and not as a dependency of another. Just seemed
  cheap to provide, not really necessary.
* `top_level.txt` contains the top-level namespace names provided by the
  package. Another one that seemed cheap to provide and is not really
  necessary.

Optionally skip installing `.dist-info` metadata directory as part of
installing Python files using a new
`OPENASSETIO_MEDIACREATION_ENABLE_PYTHON_INSTALL_DIST_INFO`
CMake option.

Signed-off-by: Elliot Morris <elliot.morris@foundry.com>